### PR TITLE
Fix and simplify Up&Down_Time constraints

### LINKED ISSUE #150: thermal_commit Up_Time and Down_Time are not indexed over the correct hours
This is in accordance with but also slightly in addition to the discussion we had earlier today. 
As far as I can tell, if `Up_Time = 1` and `hours_per_subperiod=168` then the constraints, as currently implemented, lead to

```
COMMIT[1] >= START[168]
COMMIT[2] >= START[1] + START[2]
COMMIT[3] >= START[1] + START[2] + START[3]
COMMIT[4] >= START[3] + START[4]
```
We need to make sure that this comes out right when we fix it.

### PR DESCRIPTION
**Pull request by cfe316**
The min-uptime and min-downtime constraints can be greatly simplified
using a bit of modular arithmetic. This also corrects some off-by-one
errors in the previous implementation, and changes the definition of
Up_Time to be (previous Up_Time) - 1.

Previously Up_Time = 1 meant a generator would need to be on for *two*
hours (except for some edge case bugs that resulted in either 1 or 3
hours), now it's uniformly one hour as expected.

This fixes #150 and is an alternative (plus additional fixes) of #149 .

### CODE REVIEW

**Comment by sambuddhac** [comment]
@cfe316 , the LongDurationStorage flag is missing from the genX_settings.yml file. Should I add it and set it to 1?

**Comment by sambuddhac** [comment]
> We dont use this anymore do we? Isnt LDS handled via generators_data field?
> […](#)

It's still there in the `generate_model.jl` as an argument of the `storage()` method in the `if !isempty(inputs["STOR_ALL"])` block.

**Comment by cfe316** [comment]
As discussed, this was fixed on `Dev` but not on `main`.

**Comment by xuqingyu** [comment]
@sambuddhac  dear Sam, is this merged?

**Comment by sambuddhac** [comment]
> @sambuddhac dear Sam, is this merged?

Dear @xuqingyu Qingyu, it's on the verge of getting merged. I am targeting to merge all the pending PRs today. Pretty much through with the testing for all.

**Review by sambuddhac — COMMENTED** [review]
Code reviewed. Looks correct. Tested on real systems with some deviations in results (expected?). About to double check with a toy system test.

**Comment by cfe316** [comment]
After finally creating a toy system and testing it out, I realized I *still* had an off-by-one error in the Up_Time (and probably in the Down_Time as well; I still need to check that).

**Comment by cfe316** [comment]
Here's the very simple test case if anyone is interested!

[test_Up_Time.zip](https://github.com/GenXProject/GenX/files/8327137/test_Up_Time.zip)

**Review by sambuddhac — APPROVED** [review]
Reviewed, tested, and approved

**Pull request merged**
