### PR TITLE
Build GenX and run example case nightly

### PR DESCRIPTION
**Pull request by gschivley**
Moving #491 to this PR. I'm not sure what branches/Julia versions are considered supported and should be included in the matrix -- @sambuddhac @cfe316 can you let me know if `main`/`develop` and 1.8/1.9 are sufficient?

### CODE REVIEW

**Comment by gschivley** [comment]
IIRC, the cron job won't run until it is merged into `main`. Since this PR doesn't affect GenX code it might be better to switch the target branch so it can start running nightly.

**Comment by sambuddhac** [comment]
I just have a slight doubt whether the target branch should be main or develop. Also, I don't think we're running with Julia 1.9 yet. But, I can set up for that.

**Review by gmantegna — CHANGES_REQUESTED** [review]
The Test-example job is still failing on your repo. Can you look into what's going on?

**Review by gmantegna — APPROVED** [review]
Looks good

**Pull request merged**
