### PR TITLE
Permit OrdinaryDiffEq 6

### PR DESCRIPTION
**Pull request by YingboMa**

### CODE REVIEW

**Comment by xuqingyu** [comment]
After the workflow is finished, we should also move this change to Guite_to_Project.toml.

**Comment by sambuddhac** [comment]
The build is still failing on the Julia nightly build for the DiffEq package. I suspect we gotta take a closer look at the compatible version.

**Comment by xuqingyu** [comment]
@sambuddhac at least it works for me on della. It looks like a documentation error. Please solve this ASAP, otherwise the GenX 0.3.1 is not functional.

**Comment by cfe316** [comment]
Closing because this is no longer relevant.

**Pull request closed without merging**
