### PR TITLE
Vectorize the simpler writing procedures

### PR DESCRIPTION
**Pull request by cfe316**
This is "part 1" of a series of commits that vectorize the writing procedures. This work was originally done by @xuqingyu on his `Dev_FC_QX` branch, but seems too valuable to wait until that whole branch can be merged in. I've pulled out changes to these files in the `write_outputs/` directory:

```
transmission/write_transmission_flows.jl
transmission/write_transmission_losses.jl
reserves/write_reg.jl
reserves/write_rsv.jl
ucommit/write_shutdown.jl
ucommit/write_commit.jl
ucommit/write_start.jl
capacity_reserve_margin/write_capacity_value.jl
capacity_reserve_margin/write_reserve_margin.jl
write_charge.jl
write_curtailment.jl
write_nse.jl
write_power.jl
write_power_balance.jl
write_storage.jl
write_subsidy_revenue.jl
```
All these files are relatively easy to change, as they can be done one-at-a-time: none of them effect each other. Also, compared with the original commit `519862a` I've tried to keep all the whitespace and other key lines the same, so that diffs are as small as possible (and easier to review). Altogether, these changes should not change the code outputs, except in trivial ways.
* some columns now have additional digits, i.e. `0.0` instead of `0`
* minor spelling changes, `Zone` instead of `zone`.
* columns in a slightly different order in one file.

Fixes of a known bug (lack of `* inputs["omega"]` to find annual sums, which affects 2 or 3 files), are not included, in order to make it easy to verify that outputs are otherwise identical.

------------------------------
Meanwhile, these files have changes in @xuqingyu 's commit 519862a which are, I believe, all linked together (these might be separable into two groups but I'm not sure) and I have not touched them.

```
model/core/ucommit.jl
mode/core/co2.jl
model/policies/co2_credit.jl
modle/policies/co2_tax.jl
resources/storage/storage_all.jl

write_outputs/write_co2.jl
              write_co2_cap
              write_costs
              write_net_revenue
              write_outputs
              write_storagedual
```

### CODE REVIEW

**Comment by cfe316** [comment]
I will more carefully list the changes to the outputs here, either tonight or tomorrow.

**Comment by cfe316** [comment]
Here's a summary of the changes to output files, ignoring changes which are only the printing of additional digits.

1. CapacityValue.csv: updates to trigger printing in hours when `(dual.(EP[:cCapacityResMargin][i, :])) ./ inputs["omega"]) >= 1` rather than when `dfResMar[i,t] > 0.0001`, and so on. I admit I haven't looked in to this part.

2. curtail.csv: Previously *all* generators output a "curtailed" value, now only `VRE` generators do. This is considered to be a bugfix.
3. NetRevenue.csv: columns RegSubsidyRevenue, Revenue, and Profit change due to a bugfix in RegSubsidyRevenue.
4. nse.csv: bugfix to the calculation of the `Total` column in order to account for more than one non-served energy segment for each `Zone`. Previously the sum was only over a number of entries equal to the number of zones, but it is now over all segments and all zones.
5. RegSubsidyRevenue.csv: bugfix to allow for more than one `MinCapReq` per generator. Previously only one was considered. This affects generators like offshore wind in the ISONE_Trizone example, which contribute to both 'wind' and 'offshore wind' categories.
6. ReserveMarginRevenue: slightly different column order.

Altogether, the only meaningful changes are bugfixes.

These files are unchanged (other than, possibly, additional digits in some floating point outputs):
`charge.csv`, `commit.csv`, `flow.csv`, `power_balance.csv`, `power.csv`, `reg.csv`, `reg_dn.csv`, `start.csv`, `shutdown.csv`, `storage.csv`, `SubsidyRevenue.csv`, and `tlosses.csv`.

Output files not mentioned above are not treated at all.

**Comment by cfe316** [comment]
@dharik13 @sambuddhac if you're okay with the above changes then I think this can be merged.

**Comment by sambuddhac** [comment]
> @dharik13 @sambuddhac if you're okay with the above changes then I think this can be merged.

I took a look. Seems good to me. I also assigned @dharik13 and @xuqingyu as reviewers just to make sure we have a bit more checks.

**Comment by xuqingyu** [comment]
Jacob and I wrote this, so I don't think I am qualified as a reviewer. @sambuddhac

**Comment by sambuddhac** [comment]
> Jacob and I wrote this, so I don't think I am qualified as a reviewer. @sambuddhac 

Ah ... My bad. Then, just a final check by @dharik13

**Review by sambuddhac — APPROVED** [review]
Reviewed, tested satisfactorily, and approved !!!!

**Pull request merged**
