### PR TITLE
Retrofit Modeling

### PR DESCRIPTION
**Pull request by jf-morris**
Adds retrofits.jl in the resources directory which define the retrofit technology type. Light changes were also made to investment_discharge.jl, load_generators_data.jl, generate_model.jl, and GenX.jl accommodate this inclusion. RetrofitExample was included to help test the formulation. 
A user can designate a retrofit technology using the RETRO flag and define it using the source, cost, and efficiency fields described in the README in the example. A retrofit technology can be defined with any number of source technologies, each with their own cost and efficiency. See the example for details. 
I will be out of office for a while, but I can try to get back to you if you have questions.

### CODE REVIEW

**Review by sambuddhac — APPROVED** [review]

**Comment by xuqingyu** [comment]
@sambuddhac you sure this works?

**Comment by sambuddhac** [comment]
> @sambuddhac you sure this works?

Oh, I thought this is already tested. If not, I can open it again.

**Comment by sambuddhac** [comment]
> @sambuddhac you sure this works?

Okay, I ran through the tests and it works fine. How do I make sure that the results look correct/sensible/reasonable?

**Comment by xuqingyu** [comment]
You probably want to create a test case with retrofit on your own.

**Pull request merged**
