### PR TITLE
Remove TDR_Results folders from examples

### PR DESCRIPTION
**Pull request by cfe316**
Also remove a wayward Project.toml file and a random lock file.

### CODE REVIEW

**Comment by sambuddhac** [comment]
Is the removal of TDR_Results folder to enable time domain clustering script to run instead of referring to existing tdr result, which may contain a different set of weights and/or set of rep periods than what's desired by some particular user?

**Review by sambuddhac — COMMENTED** [review]
How about including the TDR_Results in the .gitignore, rather?

**Review by sambuddhac — DISMISSED** [review]
Can we move the TDR_Results folder to .gitignore rather?

**Comment by cfe316** [comment]
> Is the removal of TDR_Results folder to enable time domain clustering script to run instead of referring to existing tdr result, which may contain a different set of weights and/or set of rep periods than what's desired by some particular user?

The TDR_Results are an *output* of the code, and we should not be in the business of storing outputs.
As an example which is focused on the multistage outputs and not specifically on the TDR outputs, I expect that the user will not need to mess with the time domain reduction settings.

A line to ignore TDR_Results is already in the .gitignore file, but these particular folders were in the repo at the time of the addition of that line, so they're still in the repo now.  This PR removes them, so that users on the latest commit won't see them as being pre-existing.

**Comment by sambuddhac** [comment]
Thanks. It totally makes sense to me now.

**Review by sambuddhac — APPROVED** [review]

**Pull request merged**
