### PR TITLE
Use the Fleccs branch's improved Morris script

### PR DESCRIPTION
**Pull request by cfe316**
This brings in several improvements to the method of morris script and interface that we made for the fleccs branch last year.

* Parameters from multiple input files can be modified. This could be useful for changing parameters from the new compound resources like fusion, thermal_storage, or VRE+Storage.
* The user no longer needs to list a copy of every generator for every parameter that needs to be changed.

### CODE REVIEW

**Comment by sambuddhac** [comment]
@cfe316 , is this still draft or complete?

**Comment by cfe316** [comment]
I needed to check out something before moving this to be ready for review.

**Comment by sambuddhac** [comment]
OK !!!

**Comment by cfe316** [comment]
Closing this because Filippo's implementation is better.

**Pull request closed without merging**
