### PR TITLE
Functionalize Dataframe loading from csv

### PR DESCRIPTION
**Pull request by cfe316**
Add a function to load a dataframe from our common sort of CSV file. This helps DRY with regard to dataframe loading settings, making code easier to read and ensuring the same options (header=1, copycols=false) are applied everywhere. Also, if we want to make dataframe loading smarter, now there's one centralized place to do it.

This commit also adds a feature that CSV files of different case can also be loaded, addressing #288 . It does not look for folders or yaml files with different cases. @RuaridhMacd it would be great if you could test this on a case-insensitive file system. 
The current implementation is sort of a minimum-working-example, it could certainly be better.

### CODE REVIEW

**Review by sambuddhac — APPROVED** [review]
I have reviewed the code modifications, tested successfully with different cases in the CSV filenames, and also pushed some further modifications for Method of Morris and Multi-Stage DDP

**Comment by RuaridhMacd** [comment]
@cfe316 I won't be able to test this on a Linux immediately, but will try to do so next early week

**Comment by RuaridhMacd** [comment]
Sounds good. Windows and Mac aren't case-sensitive in most cases. Apparently there are a few rare edge cases when using very long names. However, more and more of our runs are being done on clusters using Linux, so we're running into more Linux-issues.

**Comment by sambuddhac** [comment]
We tested on both Mac and Windows and it works perfect. Sometimes this week/weekend, I'll test on Linux as well and let you know.

**Pull request merged**
