### PR TITLE
Dev qx

### PR DESCRIPTION
**Pull request by xuqingyu**
Update CRM

### CODE REVIEW

**Review by GenXProject — CHANGES_REQUESTED** [review]
@xuqingyu 
- Checks probably failed becuase you specified Gurobi as the solver rather than Clp or Cb
-  We are missing a term for hydro in the formulation noted in the documentation of cap_reserve_margin.jl  - please add that.
- can you add more documentation (just some in line comments in the code) of the computation being carried out in write_reserve_margin_revenue.jl   - I unable to follow the dimensions of dfResMar and what dfResRevenue is.
- also there is some incorrect indenting of the "if-else" loop in write_reserve_margin_revenue.jl

**Comment by dharik13** [comment]
This looks good to me. Feel free to merge with main branch.

**Comment by sambuddhac** [comment]
I took care of the 1st and last suggestions by @GenXProject in the base/target branch to merge (i.e. Dev)... has the other two being resolved yet? @xuqingyu @nspatank @dharik13 .... is it okay to merge this PR to Dev now?

**Comment by sambuddhac** [comment]
Reviewed

**Pull request merged**
