### PR TITLE
Remove extraneous method_of_morris files

### PR DESCRIPTION
**Pull request by cfe316**
These were supposed to remain on the Morris development branch.

### CODE REVIEW

**Comment by sambuddhac** [comment]
While testing this PR, I came across this error message at writing output files:

```
ERROR: LoadError: KeyError: key :vCHARGE_FLEX not found
Stacktrace:
 [1] getindex(m::JuMP.Model, name::Symbol)
   @ JuMP ~/.julia/packages/JuMP/klrjG/src/JuMP.jl:1306
 [2] write_capacity_value(path::String, inputs::Dict{Any, Any}, setup::Dict{Any, Any}, EP::JuMP.Model)
   @ GenX ~/code/GenXPRTest/GenX/src/write_outputs/capacity_reserve_margin/write_capacity_value.jl:61
 [3] macro expansion
   @ ./timing.jl:287 [inlined]
 [4] write_outputs(EP::JuMP.Model, path::String, setup::Dict{Any, Any}, inputs::Dict{Any, Any})
   @ GenX ~/code/GenXPRTest/GenX/src/write_outputs/write_outputs.jl:162
 [5] top-level scope
   @ ./timing.jl:287
 [6] include(fname::String)
   @ Base.MainInclude ./client.jl:444
 [7] top-level scope
   @ REPL[4]:1
in expression starting at /Users/sc87/code/GenXPRTest/GenX/Example_Systems/SmallNewEngland/OneZone/Run.jl:74
```

I checked the write_capacity_value.jl at line 61 from this fork. Here's what I found:

		`temp_capvalue[FLEX_EX, :] = temp_cap_derate[FLEX_EX, :] .* ((value.(EP[:vCHARGE_FLEX][FLEX_EX, :]).data - value.(EP[:vP][FLEX_EX, :]))) .* temp_riskyhour[FLEX_EX, :] ./ totalcap[FLEX_EX, :]`

Can you please take a look once?

**Comment by sambuddhac** [comment]
While testing this PR, I came across this error message at writing output files:

```
ERROR: LoadError: KeyError: key :vCHARGE_FLEX not found
Stacktrace:
 [1] getindex(m::JuMP.Model, name::Symbol)
   @ JuMP ~/.julia/packages/JuMP/klrjG/src/JuMP.jl:1306
 [2] write_capacity_value(path::String, inputs::Dict{Any, Any}, setup::Dict{Any, Any}, EP::JuMP.Model)
   @ GenX ~/code/GenXPRTest/GenX/src/write_outputs/capacity_reserve_margin/write_capacity_value.jl:61
 [3] macro expansion
   @ ./timing.jl:287 [inlined]
 [4] write_outputs(EP::JuMP.Model, path::String, setup::Dict{Any, Any}, inputs::Dict{Any, Any})
   @ GenX ~/code/GenXPRTest/GenX/src/write_outputs/write_outputs.jl:162
 [5] top-level scope
   @ ./timing.jl:287
 [6] include(fname::String)
   @ Base.MainInclude ./client.jl:444
 [7] top-level scope
   @ REPL[4]:1
in expression starting at /Users/sc87/code/GenXPRTest/GenX/Example_Systems/SmallNewEngland/OneZone/Run.jl:74
```

I checked the write_capacity_value.jl at line 61 from this fork. Here's what I found:

		`temp_capvalue[FLEX_EX, :] = temp_cap_derate[FLEX_EX, :] .* ((value.(EP[:vCHARGE_FLEX][FLEX_EX, :]).data - value.(EP[:vP][FLEX_EX, :]))) .* temp_riskyhour[FLEX_EX, :] ./ totalcap[FLEX_EX, :]`

Can you please take a look once?

**Comment by xuqingyu** [comment]
It works fine. It is possible that the brach that you are testing is missing this 
```
		if !isempty(FLEX_EX)
			temp_capvalue[FLEX_EX, :] = temp_cap_derate[FLEX_EX, :] .* ((value.(EP[:vCHARGE_FLEX][FLEX_EX, :]).data - value.(EP[:vP][FLEX_EX, :]))) .* temp_riskyhour[FLEX_EX, :] ./ totalcap[FLEX_EX, :]
		end
```

**Comment by sambuddhac** [comment]
> It works fine on my branch. It is possible that the brach that you are testing is missing this
> 
> ```
> 		if !isempty(FLEX_EX)
> 			temp_capvalue[FLEX_EX, :] = temp_cap_derate[FLEX_EX, :] .* ((value.(EP[:vCHARGE_FLEX][FLEX_EX, :]).data - value.(EP[:vP][FLEX_EX, :]))) .* temp_riskyhour[FLEX_EX, :] ./ totalcap[FLEX_EX, :]
> 		end
> ```



> It works fine on my branch. It is possible that the brach that you are testing is missing this
> 
> ```
> 		if !isempty(FLEX_EX)
> 			temp_capvalue[FLEX_EX, :] = temp_cap_derate[FLEX_EX, :] .* ((value.(EP[:vCHARGE_FLEX][FLEX_EX, :]).data - value.(EP[:vP][FLEX_EX, :]))) .* temp_riskyhour[FLEX_EX, :] ./ totalcap[FLEX_EX, :]
> 		end
> ```

Ah ... okay. I see. I will add this now. Thanks @xuqingyu

**Comment by sambuddhac** [comment]
> It works fine on my branch. It is possible that the brach that you are testing is missing this
> 
> ```
> 		if !isempty(FLEX_EX)
> 			temp_capvalue[FLEX_EX, :] = temp_cap_derate[FLEX_EX, :] .* ((value.(EP[:vCHARGE_FLEX][FLEX_EX, :]).data - value.(EP[:vP][FLEX_EX, :]))) .* temp_riskyhour[FLEX_EX, :] ./ totalcap[FLEX_EX, :]
> 		end
> ```



> It works fine on my branch. It is possible that the brach that you are testing is missing this
> 
> ```
> 		if !isempty(FLEX_EX)
> 			temp_capvalue[FLEX_EX, :] = temp_cap_derate[FLEX_EX, :] .* ((value.(EP[:vCHARGE_FLEX][FLEX_EX, :]).data - value.(EP[:vP][FLEX_EX, :]))) .* temp_riskyhour[FLEX_EX, :] ./ totalcap[FLEX_EX, :]
> 		end
> ```

Ah ... okay. I see. I will add this now. Thanks @xuqingyu

**Comment by xuqingyu** [comment]
Which branch are you testing this on? This shouldn't happen in Dev I believe.

**Comment by sambuddhac** [comment]
I actually figured out now. It was fixed on the Dev a few days back with exactly the same fix you suggested, @xuqingyu . But, this didn't show up on the branch @cfe316 Jacob submitted this PR from. Hence, I ran into this error. I will add the if statements.

**Comment by sambuddhac** [comment]
I actually figured out now. It was fixed on the Dev a few days back with exactly the same fix you suggested, @xuqingyu . But, this didn't show up on the branch @cfe316 Jacob submitted this PR from. Hence, I ran into this error. I will add the if statements.

**Comment by cfe316** [comment]
I'm confused because I do see this as fixed on the branch I submitted.

**Comment by sambuddhac** [comment]
My apologies. Got the right one.

**Review by sambuddhac — APPROVED** [review]
Code reviewed, tested, and approved !!!

**Pull request merged**
