### PR TITLE
Cost printing update + CO2 update + policy update

### PR DESCRIPTION
**Pull request by xuqingyu**
This update includes the following features
1) break the system cost  in `write_costs.jl`, so that Fixed is separated into Investment cost, and FOM, Variable cost is separated into VOM and Fuel
2) CO2 accounting module is re-written so that CCS's captured emission is printed, and the injection cost is added.
3) CO2 policy module is re-written so that the three caps can be added simultaneously;
4) CO2 tax and CCS capture credit module is added
5) ESR and CO2 policy can now consider transmission loss;
6) Policy related expressions which used to scatter around the codes are gathered together in single files.
7) a maximum capacity limit function is added, so that multiple generators can share a common build-out upper bound
8) add a Energy Credit module so that user fan use a fixed price for clean/renewable credit (like carbon tax vs carbon cap)
9) add bunches of print functions so that the each type of payment/revenue of each market is added.
10) 24/7 module that is used for Princeton's 24/7 report is added;
11) this update prepared GenX for future update of piecewise linear heat rate

### CODE REVIEW

**Comment by xuqingyu** [comment]
@sambuddhac Hi Sam, I wonder will this be merged anytime soon?

**Comment by sambuddhac** [comment]
> @sambuddhac Hi Sam, I wonder will this be merged anytime soon?

@xuqingyu yes ... by tomorrow or Friday !!! Thanks

**Comment by sambuddhac** [comment]
@xuqingyu , for the sake of clarification: The write_emissions is split into generation emissions and load emissions flies, right?

**Comment by xuqingyu** [comment]
> 

Hi Sam, write_emissions is replaced by write_co2 and is no longer used.

**Comment by sambuddhac** [comment]
> > 
> 
> Hi Sam, write_emissions is replaced by write_co2 and is no longer used.

Thanks !!!! Taken note of.

**Comment by sambuddhac** [comment]
Also, @xuqingyu not sure if I am missing out here, but, could you please point me to the appropriate testing data folders, where you have all and any new CSVs created and saved (like Capacity_reserve_margin_slack.csv) and if it's not there yet, could you please update the PR?

**Comment by xuqingyu** [comment]
I will close this and provide a new more organized PR.

**Pull request closed without merging**
