### PR TITLE
Build GenX and run example case nightly

### PR DESCRIPTION
**Pull request by gschivley**
Nightly test to make sure a new build of GenX can run the simple test case. Also bump checkout version and Julia version to 1.9.

### CODE REVIEW

**Comment by gschivley** [comment]
See an example (failed) run from last night [here](https://github.com/gschivley/GenX/actions/runs/5341604072/jobs/9682583165)

**Comment by RuaridhMacd** [comment]
This is a great addition. It looks like the error is because we've been developing using HiGHs v1.1.4 but the workflow installed v1.5.2. I'd favor updating our HiGHS version as it looks like they've made many improvements, especially in MIP performance.

**Comment by sambuddhac** [comment]
Seems like there's a break in the build with the following error message @gschivley : 

ERROR: HTTP.Exceptions.StatusError(500, "POST", "/api/v1/jobs", HTTP.Messages.Response:
```
"""
HTTP/1.1 500 Internal Server Error
Date: Fri, 23 Jun 2023 15:16:47 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
status: 500 Internal Server Error
Cache-Control: no-cache
strict-transport-security: max-age=31536000; includeSubDomains
referrer-policy: strict-origin-when-cross-origin
x-permitted-cross-domain-policies: none
x-xss-protection: 1; mode=block
x-request-id: 57f6994a-599d-4c1b-88f9-3bd1151b4dc4
x-download-options: noopen
x-runtime: 0.390557
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
x-powered-by: Phusion Passenger(R) Enterprise 6.0.17
CF-Cache-Status: DYNAMIC
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=kR2bKQCejaZWfKWoObuH%2FdhZXIdxbVppoWm%2B5qSUfMwrhRSKHQ%2BWn5WKnMXtdNAIp7NJKwdvul3jHpN4NuwQT7Q0DaaISBrv0VXnvQefGtfyqb8jsC5Uf4OY8MSUVw%3D%3D"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 7dbdb1aa4bf5b0d3-ATL
alt-svc: h3=":443"; ma=86400
{"message":"Build processing error.","error":true,"url":""}""")
```

**Comment by gmantegna** [comment]
Converted to a draft PR as this is still in progress. @gschivley do you know why the build is failing on your fork?

**Comment by cfe316** [comment]
That error that Greg had about `simplex_dualise_strategy` is fixed in `v0.3.6`. It's worth another try!

**Comment by gmantegna** [comment]
OK, @gschivley are you able to try this out with 0.3.6?

**Comment by RuaridhMacd** [comment]
I think we've just got this working on Dolphyn, if that helps at all. We have run the Small mNewEngland examples using HiGHS

**Comment by gschivley** [comment]
Just realized that I’ve been missing all the notifications about this PR. Are there any specific actions you need from me?

**Pull request closed without merging**
