### PR TITLE
dftranspose speedup

### PR DESCRIPTION
**Pull request by RuaridhMacd**
Speeds up and reduces memory requirement of dftranspose.

Tested on the SmallNewEngland example cases and returned the same CSV files. Saw at least a 10x speedup and reduction in memory usage during the output writes. Separately tested on larger results and memory improvements appeared to increase.
Tested using the current JuliaGenXEnv modules, in particular DataFrames v0.20.2. Later versions may require a rewrite, but will also allow more flexibility in how the tranpose handles ordering or other issues.

Changes to genx_settings.yml can be rejected. Just Windows vs Mac setting.

### CODE REVIEW

**Comment by sambuddhac** [comment]
Thanks !!! I will review the PR and touch base with you before merging right after the GenX 1.0 release (hopefully tomorrow or on Wednesday)

**Comment by rmacd757** [comment]
> Thanks !!! I will review the PR and touch base with you before merging right after the GenX 1.0 release (hopefully tomorrow or on Wednesday)

Sounds good. Sorry for jumping the gun. I'm slowly updating my codebase to the new version, and will hold off any other pull requests till the release.

**Comment by sambuddhac** [comment]
No worries. Your feedback, PR, issues, e.t.c are highly valued and appreciated. Once version 1.0 is released, it'll be much easier for me to address everything.

**Comment by RuaridhMacd** [comment]
Hi, checking in on this again. Are we ok to make more PR's now?

**Comment by sambuddhac** [comment]
Hi Ruaridh,

Yes, please submit your PRs. I should be reviewing and merging them all today.

Thanks

Sam

**Comment by RuaridhMacd** [comment]
Thanks, will do.
All the best

**Comment by sambuddhac** [comment]
Reviewed and checked with all the Small examples and Real system example cases of ISO NE. The speedup for the real cases and memory reductions are very significant.

**Pull request merged**
